### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by barisx** [v-ko/misli#9]
```bash
PS D:\Programs\misli\pamet> pamet-debug
Traceback (most recent call last):
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python39\Scripts\pamet-debug-script.py", line 33, in <module>
    sys.exit(load_entry_point('pamet', 'console_scripts', 'pamet-debug')())
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python39\Scripts\pamet-debug-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "d:\programs\misli\pamet\pamet\desktop\__init__.py", line 1, in <module>
    from pamet.desktop.app import DesktopApp
  File "d:\programs\misli\pamet\pamet\desktop\app.py", line 2, in <module>
    from PySide6.QtWidgets import QApplication
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python39\lib\site-packages\pyside6-6.1.2-py3.9-win-amd64.egg\PySide6\__init__.py", line 111, in <module>
    _setupQtDirectories()
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python39\lib\site-packages\pyside6-6.1.2-py3.9-win-amd64.egg\PySide6\__init__.py", line 54, in _setupQtDirectories
    for dir in _additional_dll_directories(pyside_package_dir):
  File "C:\Users\<User>\AppData\Local\Programs\Python\Python39\lib\site-packages\pyside6-6.1.2-py3.9-win-amd64.egg\PySide6\__init__.py", line 26, in _additional_dll_directories
    raise ImportError(shiboken6 + ' does not exist')
TypeError: unsupported operand type(s) for +: 'WindowsPath' and 'str'
```

- Windows 10
- Followed installing instruction

**Comment by v-ko** [comment]
There must've been some bug introduced in the PySide6/shiboken6 point releases which was promptly fixed because I encountered the same problem, and after some digging for a solution and trial and error I got it fixed by just upgrading PySide6 and shiboken6 via pip. The only other thing I did was to add the Scripts path to my environment variable, but I doubt that's what made the difference. Do reopen the issue if upgrading does not fix it for you though.
